language: go
go: '1.12.x'

env:
  global:
    - GO111MODULE=on

install: make setup
script: make test-ci

before_deploy:
  - |
    docker login docker.io -u $DOCKER_USER -p $DOCKER_PASSWORD

deploy:
  provider: script
  script: curl -sL https://git.io/goreleaser | bash -s -- --rm-dist --skip-validate
  skip_cleanup: true
  on:
    tags: true
    branch: master

notifications:
  email: false
