language: go
go: '1.12.x'
services:
  - docker

stages:
  - test
  - name: release
    if: (repo == gojek/darkroom) AND (branch == master) AND (tag IS present)

env:
  global:
    - GO111MODULE=on

install: echo "Skip global install..."
script: echo "Skip global script..."

build_docker_image: &build_docker_image
  before_script:
    - |
      docker build -f build/Dockerfile .
      [ ! -z $TRAVIS_TAG ] && docker tag gojek/darkroom:$DOCKER_LATEST gojek/darkroom:$TRAVIS_TAG
      [ ! -z $TRAVIS_TAG ] && docker tag gojek/darkroom:$TRAVIS_TAG gojek/darkroom:$DOCKER_LATEST
      [ ! -z $DOCKER_PASSWORD ] && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      docker images

jobs:
  include:
    - stage: test
    - name: "Tests"
      install: make setup
      script: make test-ci

    - stage: release
    - name: "Release Builds"
      script: curl -sL https://git.io/goreleaser | bash -s -- --rm-dist --skip-validate
    - name: "Docker Builds"
      <<: *build_docker_image
      script: docker push gojek/darkroom:$TRAVIS_TAG && docker push gojek/darkroom:$DOCKER_LATEST

notifications:
  email: false